package org.jacobvv.permission.compiler;

/**
 * @author jacob
 * @date 19-4-25
 */
class Constants {
    static final String WARNING_TIPS = "DO NOT MODIFY THIS FILE!!! IT WAS GENERATED BY PERMISSION.";

    private static final String ANDROID_SUPPORT_PACKAGE = "androidx";
    static final String ANDROID_V4_APP = "androidx.core.app";
    static final String PERMISSION_PACKAGE = "org.jacobvv.permission";

    static final String ANNOTATION_PACKAGE = ANDROID_SUPPORT_PACKAGE + ".annotation";
    static final String PERMISSION_ANNOTATION_PACKAGE = PERMISSION_PACKAGE + ".annotation";

    static final String TYPE_ACTIVITY_COMPAT = "ActivityCompat";
    static final String TYPE_NONNULL = "NonNull";
    static final String TYPE_REQUEST_SUFFIX = "_PermissionRequest";
    static final String TYPE_REQUEST = "PermissionRequest";
    static final String TYPE_UTILS = "PermissionUtils";

    static final String METHOD_REQUEST = "requestPermissions";
    static final String METHOD_ISEMPTY = "isEmpty";
    static final String METHOD_REMOVEALL = "removeAll";

    static final String METHOD_REQUEST_SUFFIX = "_WithCheck";
    static final String METHOD_RESULT = "onRequestPermissionsResult";
    static final String METHOD_SHOULD_REQUEST = "shouldPermissionRequest";
    static final String METHOD_SHOULD_RATIONALE = "shouldShowRationale";
    static final String METHOD_CHECK = "checkPermissionResult";
    static final String METHOD_PROCEED = "proceed";
    static final String METHOD_CANCEL = "cancel";

    static final String VAR_REQUEST_CODE_PREFIX = "REQUEST_";
    static final String VAR_PERMISSIONS_PREFIX = "PERMISSION_";

    static final String VAR_TARGET = "target";
    static final String VAR_REQUEST_CODE = "requestCode";
    static final String VAR_PERMISSIONS = "permissions";
    static final String VAR_GRANT_RESULTS = "grantResults";
    static final String VAR_DENIED_FOREVER = "deniedForever";
    static final String VAR_DENIED = "denied";
    static final String VAR_REQUEST = "request";
}
