package org.jacobvv.permission.compiler;

/**
 * @author jacob
 * @date 19-4-25
 */
class Constants {
    static final String WARNING_TIPS = "DO NOT MODIFY THIS FILE!!! IT WAS GENERATED BY PERMISSION.";

    private static final String ANDROID_SUPPORT_PACKAGE = "android.support";

    static final String ANNOTATION_PACKAGE = ANDROID_SUPPORT_PACKAGE + ".annotation";
    static final String PERMISSION_PACKAGE = "org.jacobvv.permission";

    static final String TYPE_NONNULL = "NonNull";
    static final String TYPE_UTILS = "PermissionUtils";

    static final String METHOD_RESULT = "onRequestPermissionsResult";
    static final String METHOD_CHECK = "checkPermissionResult";

    static final String PARAM_TARGET = "target";
    static final String PARAM_REQUEST_CODE = "requestCode";
    static final String PARAM_PERMISSIONS = "permissions";
    static final String PARAM_GRANT_RESULTS = "grantResults";

    static final String VAR_DENIED_FOREVER = "deniedForever";
}
